// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("flightrecorder")
	ScopeName = "github.com/florianl/flightrecorderreceiver"
)

const (
	ProfilesStability = component.StabilityLevelAlpha
	MetricsStability  = component.StabilityLevelBeta
)
